# Generated by Django 2.2.7 on 2019-11-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='worker', max_length=255)),
                ('start_date', models.DateField()),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
    ]
