# Generated by Django 2.2.7 on 2019-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_thirty_day_alert',
            field=models.BooleanField(default=False),
        ),
    ]
