# Generated by Django 2.2.7 on 2019-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_has_thirty_day_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='has_thirty_day_alert',
            field=models.BooleanField(blank=True),
        ),
    ]
