# Generated by Django 2.2.7 on 2019-11-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20191120_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
