# Generated by Django 2.2.7 on 2019-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
