# Generated by Django 2.2.7 on 2019-11-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20191118_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
