# Generated by Django 2.2.7 on 2019-11-18 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('last_modified', models.DateField(default=datetime.datetime(2019, 11, 18, 0, 21, 44, 559782, tzinfo=utc))),
                ('quantity', models.IntegerField()),
                ('need_to_reorder', models.BooleanField(default=False)),
                ('reorder_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_quantity', models.IntegerField()),
                ('end_quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
    ]
