# Generated by Django 2.2.7 on 2019-11-18 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 2, 39, 18, 25823, tzinfo=utc)),
        ),
    ]
