# Generated by Django 2.2.7 on 2019-11-18 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191118_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 4, 12, 20, 5174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_point',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
