# Generated by Django 2.2.7 on 2019-11-18 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191118_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 4, 25, 48, 888255, tzinfo=utc)),
        ),
    ]
