# Generated by Django 2.2.7 on 2019-11-20 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20191118_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 4, 34, 11, 534557, tzinfo=utc)),
        ),
    ]
