# Generated by Django 2.2.7 on 2019-11-20 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20191120_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 4, 36, 35, 842098, tzinfo=utc)),
        ),
    ]
