# Generated by Django 2.2.7 on 2019-11-20 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20191120_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 5, 47, 43, 669905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='need_to_reorder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
