# Generated by Django 2.2.7 on 2019-11-20 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20191120_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 5, 50, 42, 863034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='need_to_reorder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
