# Generated by Django 2.2.7 on 2019-11-20 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20191120_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 17, 57, 0, 385117, tzinfo=utc)),
        ),
    ]
