# Generated by Django 2.2.7 on 2019-11-22 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20191120_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 3, 10, 5, 666570, tzinfo=utc)),
        ),
    ]
