# Generated by Django 2.2.7 on 2019-11-22 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20191122_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 22, 39, 22, 540389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
