# Generated by Django 2.2.7 on 2019-11-22 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20191122_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 22, 40, 19, 830743, tzinfo=utc)),
        ),
    ]
